// <auto-generated />
using System;
using MealPlanner.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MealPlanner.Api.Migrations
{
    [DbContext(typeof(MealPlannerDbContext))]
    partial class MealPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EdamamFoodId")
                        .HasColumnType("text")
                        .HasColumnName("edamam_food_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("EdamamFoodId")
                        .IsUnique();

                    b.ToTable("ingredient", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.NutrientOrganMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BodySystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("body_system");

                    b.Property<string>("ImpactDescription")
                        .HasColumnType("text")
                        .HasColumnName("impact_description");

                    b.Property<string>("NutrientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nutrient_name");

                    b.Property<string>("OrganName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("organ_name");

                    b.Property<string>("SourceCitation")
                        .HasColumnType("text")
                        .HasColumnName("source_citation");

                    b.HasKey("Id");

                    b.HasIndex("NutrientName")
                        .IsUnique();

                    b.ToTable("nutrient_organ_mapping", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.PlanSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meal_type");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.Property<DateOnly>("SlotDate")
                        .HasColumnType("date")
                        .HasColumnName("slot_date");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("RecipeId");

                    b.ToTable("plan_slot", null, t =>
                        {
                            t.HasCheckConstraint("ck_plan_slot_meal_type", "meal_type IN ('breakfast', 'lunch', 'dinner', 'snack')");

                            t.HasCheckConstraint("ck_plan_slot_servings_positive", "servings > 0");
                        });
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("CookTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cook_time_minutes");

                    b.Property<string>("CoverColour")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("#E8F5E9")
                        .HasColumnName("cover_colour");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cuisine")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cuisine");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("PrepTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("prep_time_minutes");

                    b.Property<int>("Servings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("servings");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("private")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.ToTable("recipe", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_servings_positive", "servings > 0");

                            t.HasCheckConstraint("ck_recipe_visibility", "visibility IN ('private', 'public')");
                        });
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("CaloriesPer100G")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal?>("CarbsG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("carbs_g");

                    b.Property<string>("EdamamFoodId")
                        .HasColumnType("text")
                        .HasColumnName("edamam_food_id");

                    b.Property<string>("EdamamMeasureUri")
                        .HasColumnType("text")
                        .HasColumnName("edamam_measure_uri");

                    b.Property<decimal?>("FatG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fat_g");

                    b.Property<decimal?>("FibreG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("fibre_g");

                    b.Property<Guid>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<decimal?>("ProteinG")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("protein_g");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("recipe_ingredient", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_ingredient_quantity_positive", "quantity > 0");
                        });
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BackgroundStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("background_step_id");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instruction");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipe_id");

                    b.Property<int>("StepNumber")
                        .HasColumnType("integer")
                        .HasColumnName("step_number");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_type");

                    b.Property<int?>("TimerSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timer_seconds");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundStepId");

                    b.HasIndex("RecipeId", "StepNumber")
                        .IsUnique();

                    b.ToTable("recipe_step", null, t =>
                        {
                            t.HasCheckConstraint("ck_recipe_step_step_number_positive", "step_number > 0");

                            t.HasCheckConstraint("ck_recipe_step_timer_positive", "timer_seconds IS NULL OR timer_seconds > 0");

                            t.HasCheckConstraint("ck_recipe_step_timer_required", "step_type <> 'timed' OR timer_seconds IS NOT NULL");

                            t.HasCheckConstraint("ck_recipe_step_type", "step_type IN ('sequential', 'background', 'timed')");
                        });
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.ShoppingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<bool>("IsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_checked");

                    b.Property<bool>("IsManual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manual");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid")
                        .HasColumnName("list_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ListId");

                    b.ToTable("shopping_item", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.ShoppingList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("shopping_list", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("user_profile", (string)null);
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WeekStart")
                        .IsUnique();

                    b.ToTable("weekly_plan", null, t =>
                        {
                            t.HasCheckConstraint("ck_weekly_plan_status", "status IN ('draft', 'confirmed')");
                        });
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.PlanSlot", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.WeeklyPlan", "Plan")
                        .WithMany("Slots")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Domain.Entities.Recipe", "Recipe")
                        .WithMany("PlanSlots")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.Recipe", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.UserProfile", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.RecipeIngredient", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MealPlanner.Api.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.RecipeStep", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.RecipeStep", "BackgroundStep")
                        .WithMany("DependentSteps")
                        .HasForeignKey("BackgroundStepId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Api.Domain.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackgroundStep");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.ShoppingItem", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.Ingredient", "Ingredient")
                        .WithMany("ShoppingItems")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Api.Domain.Entities.ShoppingList", "List")
                        .WithMany("Items")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("List");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.ShoppingList", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.WeeklyPlan", "Plan")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MealPlanner.Api.Domain.Entities.UserProfile", "User")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.WeeklyPlan", b =>
                {
                    b.HasOne("MealPlanner.Api.Domain.Entities.UserProfile", "User")
                        .WithMany("WeeklyPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("ShoppingItems");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("PlanSlots");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.RecipeStep", b =>
                {
                    b.Navigation("DependentSteps");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.ShoppingList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Recipes");

                    b.Navigation("ShoppingLists");

                    b.Navigation("WeeklyPlans");
                });

            modelBuilder.Entity("MealPlanner.Api.Domain.Entities.WeeklyPlan", b =>
                {
                    b.Navigation("ShoppingLists");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
